### ISSUE TITLE
Figure out how to deploy webapp safely when migrations are involved.

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#100]
# TODO
- [x] [Finish this slack conversation](https://penny-university.slack.com/archives/C41QX2KRS/p1578456853001400) ~ Scott recommends migrating w/ every deployment, but ideally separate out migration PRs so they're easier to review.
- [x] Add back in the migration script.
- [x] ~Do something so that we snapshot our db before every merge. (We won't always be able to do this. But it will protect us for now.)~ do it manually for now

**Comment by JnBrymn** [comment]
https://github.com/penny-university/penny_university/blob/master/Procfile now has migration again
