### ISSUE TITLE
Implement RSVP buttons for /penny chat

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#117]
[As represented in the mockup here](https://docs.google.com/presentation/d/1Wwlzly5gC9uPLl_Jj2Jxf6Br2437TxYcssL0edDuO7s/edit#slide=id.g6e730f2f0b_0_23)

Implemented in https://github.com/penny-university/penny_university/pull/126

# TODO
- [x] Add yes and no RSVP buttons to form (but only for real share)
- [x] Split PennyChat into Chat part and new Invitation model ~ Ship https://github.com/penny-university/penny_university/issues/118
- [x] Make it turn `Invited` into `Attendee` participant if someone accepts
- [x] Make it turn `Invited` into `NonAttendee` participant if someone doesn't accept
- [x] Make it notify the organizer (but only on the first time that someone clicks)
- [x] Make sure it works from both public invites and private
- [x] (Stretch) notify the RSVPer that they organizer will be notified.
- [x] Test
  - [x] Someone can have two penny chats shared at once, make sure that only the correct one gets changed ~ demonstrated here https://github.com/penny-university/penny_university/pull/126#issuecomment-586750573
- [x] Little stuff
  - [x] `@is_action_id('penny_chat_can_attend')` - should this be `@is_action_id('penny_chat_can_attend', 'penny_chat_can_not_attend')` ~ yes, changed
  - [x] Make sure that the notification timestamp, user, and name are correct ~ see in https://github.com/penny-university/penny_university/pull/126#issuecomment-586750573
  - [x] Better document flow of penny chat in docstring
  - [ ] ~Document all PennyChat models~ ~ punted
  - [x] remove `TODO!`
- [x] Record evidence of correctness (create new qa user) ~ ~ https://github.com/penny-university/penny_university/pull/126#issuecomment-586750573
- [ ] Review and Deploy
  - [ ] Shell in and delete any PennyChat that has status=Draft
  - [ ]  multiply participant statuses by 10 (`DRAFT_STATUS = 10` etc.)
- [x] Add Follow-on tickets
  - Ability to edit Penny Chats (and notify attendees and update existing invitation messages) ~ https://github.com/penny-university/penny_university/issues/128
  - Ability to invite people by email (sends email!!!) (add in miniature PennyU advertisement) ~ https://github.com/penny-university/penny_university/issues/129
  - Incorporate hangout or zoom link invitation ~ https://github.com/penny-university/penny_university/issues/130
  - Incorporate public google doc in invitation ~ https://github.com/penny-university/penny_university/issues/131
  - make it update the update the invitation posts with the members attending. ~ https://github.com/penny-university/penny_university/issues/127

**Comment by JnBrymn** [comment]
I updated the `role` field to be 10x the current value
```
$ heroku pg:psql -a penny-university
--> Connecting to postgresql-concave-05371
psql (11.5, server 11.6 (Ubuntu 11.6-1.pgdg16.04+1))
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

penny-university::DATABASE=> update pennychat_participant set role = role * 10  where role < 10;
UPDATE 226
```

**Comment by JnBrymn** [comment]
There are no production DRAFT penny chats
```
penny-university::DATABASE=> select * from pennychat_pennychat where status = 10;
 id | title | description | date | status 
----+-------+-------------+------+--------
(0 rows)
```
