### ISSUE TITLE
Remind attendees of details just before the chat

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#132]
# TODO
- [x] Create reminder comment post
- [x] Create background job that does all the reminding for PennyChats that are coming in the next hour.
- [x] Make sure the reminder only reminds for a penny chat once
- [x] Update scheduled events in heroku
  * And make sure we're not using too many resources
- [x] Test
- [x] Cleanup (TODO!)
- [x] Deploy
- [x] Proof of Correctness ~ I tried `/penny chat` for a chat within 40 minutes and it reminded me.

**Comment by JnBrymn** [comment]
# Old Description

### UPDATE
This ticket is no longer valid. I'm first doing https://github.com/penny-university/penny_university/issues/153 to move slack messaging into background tasks. Then I will reevaluate this.

### TODO
- [x] When user says they can attend, schedule reminder - make sure it is presented in their timezone
- [x] When user says the can no longer attend, delete reminder.
- [ ] When Chat date/time is changed, change the reminders for everyone.
- [ ] Test
  - [ ] Make sure timezones make sense!
- [ ] Show evidence of correctness

### NOTES
* https://api.slack.com/messaging/scheduling

### Considering Alternative Implementation
In order to complete the above we would have to add potentially LOTS more requests inside of the `submit_details_and_share` method in order to delete all the participants scheduledMessages and post new ones. (So `2*num_participants` more requests). This is the one that I'm already concerned will timeout.

So I'm looking into a combination of the [Heroku Scheduler](https://devcenter.heroku.com/articles/scheduler) and [Django Background Tasks](https://django-background-tasks.readthedocs.io/en/latest/).
