### ISSUE TITLE
Allow organizers to edit their PennyChats

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#136]
# TODO
- [x] Upon sharing a Penny Chat
  - [x] The necessary data will be recorded so that the individual shares can be updated.
  - [x] The organizer will get a button to edit their event.
- [x] Upon clicking the edit button
  - [x] If text or title is edited then reshare the new information on all places it's already shared
  - [x] If more users are created or removed then you have to create new shares or delete old ones.
- [x] test
- [x] review #138
- [x] ship #138

**Comment by JnBrymn** [comment]
Note to self 
```
# TODO! START in cheate_penny_chat - if there is for some reaons more than one invitation drafts then the user can no longer use /penny chat
        # because this errors. Fix by try/except around this and if there are problems, set all the STATUSES to WEIRD and create a new one
        # THEN you're ready for trying to get the penny chat by the id stored in value
```

**Comment by JnBrymn** [comment]
I want to make a processor like this to stick in front of all the processors for `PennyChatBotModule`
```python
@event_processor_decorator
def gather_penny_chat_data(event):
    try:
        value = json.loads(event['actions'][0]['value'])
        penny_chat_invitation = PennyChatInvitation.objects.get(id=value['penny_chat_id'])
        event['penny_chat_data'] = value
        event['penny_chat_data']['penny_chat_invitation'] = penny_chat_invitation
        return event
    except:  # noqa
        import ipdb;ipdb.set_trace()
        requests.post(event['response_url'], json={'delete_original': True})
        self.slack_client.chat_postEphemeral(
            channel=event['channel']['id'],
            user=event['user']['id'],
            text=(
                "We are sorry, but an error has occurred and the Penny "
                "Chat you are trying to edit is no longer available."
            ),
        )
        return
```

**Comment by JnBrymn** [comment]
all boxes checked!
