### ISSUE TITLE
Finish Dev Setup Doc

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#163]
# TODO
- [x] Move [these docs](https://docs.google.com/document/d/1d3o2IkOg4z93c-l6w_cF8kKCM36DkxTq8Wpj7JMbQtw/edit) into a markdown file
- [x] Add Javascript stuff
- [x] Turn README into a table of contents into these files. (including placeholder file for Production Setup)
- [ ] Bonus points - a Product Catalog doc
