### ISSUE TITLE
Create Reminder to do Penny Chat Followup

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#191]
# TODO
- [x] Create `send_followup_reminder_and_mark_chat_as_completed`
- [x] Create blocks for followup
- [x] Tests and remove TODO! 

# Description
After a PennyChat, Participants should be reminded to do a Penny Chat followup. Probably wait till an hour after the start of the Penny Chat. The text should carry the feeling of "this is a nice way of saying thanks" rather than "this is the thing you must do". We should link out to a page in the web app that shows the Penny Chat and has a text box ready to type into.

**Comment by CoreyAR** [comment]
The chat detail endpoint is at `/chats/:id`. We can direct them there with a `followUp=true` query parameter so we can show them a friendly message and prepare the screen to create a followup.

**Comment by JnBrymn** [comment]
Blocked on https://github.com/penny-university/penny_university/issues/245
