### ISSUE TITLE
Create Integration Tests

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#203]
# NEW GOAL
Make logger controlled by env var that will print out copy-pastable code for integration tests. When an endpoint is called, it will print out
```
client = APIClient()
response = client.post('/the/endpoint/', data={...})
assert response == 'whatever'
``` 

And if there are any clients to external services, then the clients can be decorated so that their input/output is printed too as
```
slack_client = mock.Mock()
slack_client.do_stuff.side_effect = [resp1, resp2,...]
...
assert slack_client.call_args = call('this')
```

# TODO
- [x] Figure out how to run background_task jobs synchronously ~ 84016e508f08
- [x] Make sure we can intercept messages to slack. ~ I made a slack client provider for this that we can easily mock
- [x] Make some actual tests.
  - /penny chat ~ done
  - ~onboarding~ ~ decided I was too tired
  - ~reminders~ ~ already tested sufficiently
- [x] Make some form of logging so that it's easier to make integration tests in the future. All you have to do is turn on a env var and then you can copy-paste logs as tests.
- [x] Document
- [x] Add tests to GitHub workflow
- [x] Make pytest run with the `ci` settings file and remove all the places where I used `backgrounded_task.now(*)` in the tests.
- [x] Make slack notifications for the production deploy.

**Comment by JnBrymn** [comment]
# Original TODOs
- [ ] Create a quick-n-dirty flask app that records all its traffic and has a single defined endpoint that that can tell you if some call has been seen.
- [ ] Set etc. hosts on actions runner to redirect slack traffic to the flask app.
- [ ] Make sure that strategy _actually works_ in the github action
- [ ] Write tests to test that the proper slack endpoints are being called.

**Comment by nchouard** [comment]
This ticket is done, we have a new one for the new integration tests.
