### ISSUE TITLE
Make merge to master workflow send messages to slack upon success or failure

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#221]
# TODO
- [ ] ~Start testing with Python 3.9~ ~ eh... we'll try later
- [x] Split out testing from deployment
- [x] Make sure that success or fail of deploy prints to slack

# Original description
You can use if: failure() in a step to only run if any previous step has failed. Might be able to if: failure() and github.event == 'push'?

I'd pull those slack message sends into different steps from the deploy step

this might also be a smart time to split up test-frontend and test-backend from deploy if the tests have really been run on the same codebase.

**Comment by JnBrymn** [comment]
@sburns, I'm thinking about splitting ci.yml (https://github.com/penny-university/penny_university/blob/master/.github/workflows/ci.yml) into two files 1) test-frontend and test-backend and 2) deploy. My rationale is that master has already been merged into the PR branch and tested before it is possible for me to push to master and close the PR. Therefore there is no need to test the build again because it's the same code and has already been tested. If I can split out the files, then I can simplify deploy by removing all the `if: github.event_name == 'push'` lines.

Thoughts?

**Comment by sburns** [comment]
Do you have the setting enabled on the repo that requires PRs to be up to date with master before merging?

**Comment by JnBrymn** [comment]
yup 
![image](https://user-images.githubusercontent.com/566533/84182377-eb988100-aa4f-11ea-981e-6b166601573e.png)

**Comment by nchouard** [comment]
@JnBrymn I believe you finished this one?
