### ISSUE TITLE
Set up sentry to have visibility of exceptions.

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#242]
# todo
- [x] `heroku addons:create sentry -a penny-john`
- [x] Push an intentional error to QA and make sure it writes to sentry ~ didn't work at first, but finally got it working; see https://github.com/penny-university/penny_university/issues/242#issuecomment-647074686 and discussion above that
- [x] Wrap known error points
  - Read this first https://docs.sentry.io/platforms/python/
  - then capture every place where we have and `except`
- [x] `heroku addons:create sentry -a penny-university` and turn off the filter for web crawlers
- [x] Update docs 
  - how to log errors
  - `heroku addons:open sentry` to view them
- [ ] Ship

# notes
* python sentry sdk https://pypi.org/project/sentry-sdk/
* django sentry https://docs.sentry.io/platforms/python/django/
* heroku sentry https://devcenter.heroku.com/articles/sentry

**Comment by JnBrymn** [comment]
Tried this and it worked:

```python
$ SENTRY_DSN=`heroku config:get SENTRY_DSN -a penny-john` mage shell
In [1]: from sentry_sdk import capture_exception                                                                                                                                     

In [2]: try: 
   ...:     1/0 
   ...: except Exception as e: 
   ...:     capture_exception(e) 
   ...:        
```

Ran `heroku addons:open sentry`

saw 
![image](https://user-images.githubusercontent.com/566533/84730077-df825700-af5a-11ea-8a03-d02b56555f13.png)

**Comment by JnBrymn** [comment]
I'm having trouble understanding what's happening here. It seems that if I trigger an error in a view  by directly visiting a URL then the exception is logged in sentry. But if the request to the same endpoint comes from Slack, then _even thought it hits the exception_ sentry doesn't get updated.

Here's what I tried:
    - I issued `/penny chat` from QA slack and saw in heroku logs that it hit my error, but sentry never received an update.
    - I directly hit http://penny-john.herokuapp.com/bot/command/ (the same endpoint) and saw in heroku logs that it hit the exception and the update was sent to sentry.

_Why?_

**Comment by JnBrymn** [comment]
Still not having much luck. Stuff I've  tried:

`/hook/` is the endpoint that listens to all messages; I've added code to make it print our request and environment and then throw an error.

* If I type a letter in slack and press return, this goes to /hook/, I see the error in the logs but nothing in sentry
* If I point my browser to penny-john.herokuapp.com/bot/hook/ (http or https) then I see the error in the logs AND the error in sentry.


The `request.environ` variable looks different. In the case that works I see these keys present
```
'CSRF_COOKIE',
 'HTTP_ACCEPT_LANGUAGE',
 'HTTP_CACHE_CONTROL',
 'HTTP_COOKIE',
 'HTTP_UPGRADE_INSECURE_REQUESTS' =
```
which are not present in the failed one.


And of the keys that are shared, here are the ones with different values that I deemed meaningful:
```
REQUEST_METHOD
	WORKS:GET
	FAILS:POST

HTTP_USER_AGENT
	WORKS:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
	FAILS:Slackbot 1.0 (+https://api.slack.com/robots)

HTTP_ACCEPT
	WORKS:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
	FAILS:*/*

HTTP_X_FORWARDED_PROTO
	WORK:http
	FAILS:https

wsgi.url_scheme
	WORK:http
	FAILS:https
```

**Comment by JnBrymn** [comment]
I tried this pattern for manually catching exceptions
```
try: 
    1/0 
except Exception as e: 
    capture_exception(e) 
```
and it exhibited the same behavior. From Slack no sentry, direct from browser sentry. So if I land my change then it will serve no purpose.

**Comment by JnBrymn** [comment]
Finally able to sensibly replicate a slack call that causes the problem with

```
curl -XPOST "https://penny-john.herokuapp.com/bot/command/"  --header "Content-Type: application/json" --compressed --header "Connect-Time: 0" --header "Connection: close" --header "Total-Route-Time: 0" --user-agent "Slackbot 1.0 (+https://api.slack.com/robots)" --header "Via: 1.1 vegur" --header "X-Forwarded-For: 54.163.203.2" --header "X-Forwarded-Port: 443" --header "X-Forwarded-Proto: https" --header "X-Request-Id: 6b38d7e1-d5e6-4af7-b047-7fbdbbde39f1" --header "X-Request-Start: 1592705759050" --header "X-Slack-Request-Timestamp: 1592705759" --header "X-Slack-Retry-Num: 3" --header "X-Slack-Retry-Reason: http_error"
```

Now it's time to bisect the headers and see what's causing the problem!

**Comment by JnBrymn** [comment]
And the winner is..... 
```
curl -XPOST "https://penny-john.herokuapp.com/bot/command/"  --user-agent "Slackbot 1.0 (+https://api.slack.com/robots)"
```

**Comment by JnBrymn** [comment]
Finally solved it! Whew... https://github.com/getsentry/sentry-python/issues/354 this fellow was having the same problem as I. Turns out sentry filters out "known web crawlers". I'm not sure why `--user-agent "Slackbot"`, but when I went to our sentry's `[Project] » Project Settings » Inbound Filters ` (which is super hard to find), there is an option to turn off filtering of web crawlers. If this causes problems later, we might have to investigate further options.
