### ISSUE TITLE
Require LogIn upon Followup submit rather than Followup start edit.

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#245]
# Description 
Currently when the user attempts to start a FollowUp we require them to log in (or if they don't have an account to sign up). But I'm concerned that people will see the sign up wall and neither sign up nor finish editing their followup.

An improved flow would be to check log in AFTER upon the submission of the followup. Once the user has made the investment in writing a followup, they are much more likely to actually complete the signup. But we must make sure to preserve the followup text through login or even through sign up, **or even through "forgot email"**.

# Product Flow
* Unauthed user attempts to make followup
* Upon submit they get a "sign up/in" modal.
* If the already have an account, then they just sign in and the form submits at that point and saves their followup.
* If they don't have an account, 
  * they go through the start of sign up flow and upon the submission of the signup we also save their followup... but with an unverified user
  * once they finish verification their user is verified and their followup can be displayed

# TODO
- [ ] ...
- [ ] Absolutely make sure there is no way to lose a user's text during a log-in or sign-up flow.
- [ ] Make sure that users remain logged in for a while (forever?) on our website.
- [ ] Make sure that followups from unauthenticated users aren't displayed.
- [ ] ...

**Comment by JnBrymn** [comment]
@CoreyAR you talked about keeping the user text on the page and doing the signup flow through a modal. I don't know how this would work, but I like the idea.

**Comment by CoreyAR** [comment]
I think you could accept the initial follow up with their signup request. Optionally, it could be hidden until they verify their email. The email verification is where it gets tricky.

Alternatively, we could store it somehow and redirect and bring it back when the user logs back in

**Comment by nchouard** [comment]
On Tuesday, Corey worked through implementing this on the frontend on this branch: https://github.com/penny-university/penny_university/tree/issue-245-save-unauthed-followup. Now we need to implement the API on the backend to hand these requests. 

## Details
The frontend is expecting that several endpoints will accept a field called `follow_up_text`, which first I propose we rename to `follow_up_content`, to match the current field names in the follow up schema. These endpoints need to be updated to save a follow up to the user (which can be found via their email, that will also be passed back). These are each of the endpoints that need to be able to save a follow up:
* Register User - `/api/auth/register/`
* Resend Verification Email - `/api/auth/verification-email/`
* Log In - `/api/auth/login` This endpoint is currently implemented by the auth library we are using. [Check the documentation](https://dj-rest-auth.readthedocs.io/en/latest/configuration.html) for how to override the serializer and [check the code](https://github.com/jazzband/dj-rest-auth/blob/master/dj_rest_auth/serializers.py).

We also only want to retrieve follow ups that have been created by a verified user.

## Requirements
- [ ] Implement saving a follow up for each of the endpoints above
- [ ] Add a filter to the Follow Ups query set that only gets ones from verified users
- [ ] Add tests

**Comment by nchouard** [comment]
Done but never closed
