### ISSUE TITLE
Automate match making

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#299]
# Context
Can we do something like a clone of Donut to match people together for conversations? It would be nice to do this with a PennyUniversity slant, like matching people to learn because they share similar interests rather than just matching random people. But matching random people is also interesting sometimes because of the serendipity of meeting someone that had _different_ experiences.

# todo
- [x] **request matches** - Create function to  send `request_match_blocks` on day 0 to each topic channel (using pieces from `request_matches.py`)
- [x] **make matches** - Use `matchmaker.MatchMaker` to match people on day 7 (Using pieces from `make_matches.py`)
- [x] **remind matches** - Automatically remind people on day 14 (using pieces from `remind_matches.py`)
- [x] Cleanup whatever remains of `request_matches.py` `make_matches.py` and `remind_matches.py` commands and the code they used.
- [x] Make background task (see penny_university/management/commands/background_tasks.py as an example):
  * Day 0 **request matches** 
  * Day 7 **make matches**
  * Day 14 **remind matches**
  * Reschedule everything again to start on day 15 so that it happens about twice a month and so that it starts on a different day of the week each time.
- [x] Test
- [x] Document how this feature works and how to set it up.
- [ ] Release
- [ ] Schedule background task in Heroku
- [x] Remove donut from our slack.
- [ ] Follow-on Issues
  - [ ] gather data for people's match records (e.g. what portion of the time do their matches turn into chats?) and boost matches when both people are not good at actually following through with matches because we don't want them to burn others out.
  - [ ]  consider if we want to keep having the bi-weekly match requests posted in each channel, or do we want to replace it with opt-out flow (and the tools in the web app to manage preferences)

**Comment by nchouard** [comment]
Steps
1. Gather interests
2. Decide whether to automate or do manually at first

Some options:
* Ask people if they want to meet someone before starting the conversation
* Drop people into a conversation with the bot
* Both?

**Comment by JnBrymn** [comment]
# here's how to make a better donut than donut

Donut has a problem in that if you join it's channels you will be forced to be introduced to chat with others. But the channels you typically join for donut our topic-less so it's difficult to have a good conversation. INSTEAD we could make Penny ask people in each channel if they would like like to meet with other people from this channel, and they can opt in if they like, but they don't have to leave the channel. This way you can add PennyDonut to an existing channel and give the benefits of Donut only to those people that want it. And you also get a better topic because they channel already has a topic like #philosophy. This also works well for team channels.

**Comment by deadbender** [comment]
> And whoever does this, look into the background_tasks somehow.

Took a quick look just as I was scrolling through here and here's the solution I'm seeing with background_tasks: 

Store a variable somewhere containing the date that matches were last sent out. When background_tasks is run, check if the timestamp has been 2 weeks. If true, run a second function that just runs the command in request_matches. Same thing only different timing on remind_matches.

It sounds fairly easy to implement, but my one fear is the truth in a comment in the file.

> as we grow, the reminder methods here will take longer to send and therefor will delay tasks that should be run relatively quickly in run_process_tasks

Question is, what's a more efficient way of adding in a new scheduler task in background_tasks than this? Especially when it will auto run everything every 10 minutes. The best solution may just be to just add in a new job in the Heroku Scheduler.

**Comment by JnBrymn** [comment]
I ran into a problem with background_tasks. I intended to have an `initialize_automated_matching` django command that set up periodic match making for a particular slack team. It would do this by running `request_matches(repeat=FIFTEEN_DAYS)` where `request_matches` is decorated by `@background`. Unfortunately, there's a problem in that if the task ever errors out, then it the task is canceled thereafter. [The problem is in the bg_runner function.](https://github.com/arteria/django-background-tasks/blob/e04d44c07110443bbdeb8cb14effbe497ddbb98d/background_task/tasks.py#L23). In the try, if the task completes successfully, then only there is the next instance created (`create_repetition`). In the exception when the task fails, we `reschedule`, but this is not to set it up to run next time, rather it just gets retried again now... so it's not the same thing.

So that sucks.

To remedy the situation, note that when the task fails a django signal is called for `task_error`. So when we set up the task the first time, we'll also set up a signal receiver callback to set the task back up again if there's an error. This is stupid, and brittle, but I bet it will work.

**Comment by JnBrymn** [comment]
If you'll recall, before the break I set up my QA environment to do automated tests and we saw that `_request_matches_task` worked because Colin, Sydney, Nick and I were able to sign up to meet in a few different channels.

Today I made a couple of small changes and deployed to QA and ran this test there:
```python
>>> from matchmaking.tasks import _make_matches_task, _remind_matches_task
>>> _make_matches_task.now('TNJ631DFU')  # this is me manually calling the the next step which makes the matches

# here's the output
make_matches for TNJ631DFU: ['colin@cpdev.me', 'jfberryman@gmail.com'] in  penny-university
make_matches for TNJ631DFU: ['nick.chouard@gmail.com', 'sydneycnoh@gmail.com'] in  general
set up _remind_matches_task for TNJ631DFU
```

I looked in slack and it sent me this message
![image](https://user-images.githubusercontent.com/566533/103607190-f16b1d80-4edd-11eb-880f-6e9deac22fe2.png)


Then I ran the next step:
```python
>>> _remind_matches_task.now('TNJ631DFU')
remind_matches for TNJ631DFU
```
And I received this message in slack
![image](https://user-images.githubusercontent.com/566533/103607240-0b0c6500-4ede-11eb-9593-6a79a303d037.png)

I think I'll deploy it!

**Comment by JnBrymn** [comment]
### evidence of completion
I deployed and ran `$ heroku run ./manage.py initialize_automated_matching --slack_team_id=T41DZFW4T -a penny-university` to get everything set up. 

I immediately checked the tasks table and saw this
```python
>>> Task.objects.all()
<TaskQuerySet [<Task: matchmaking.tasks._request_matches_task>]>
```
indicating that the `_request_matches_task` task had been set up.

And soon thereafter (<1 minute) saw.
```python
>>> Task.objects.all()
<TaskQuerySet [<Task: matchmaking.tasks._make_matches_task>, <Task: matchmaking.tasks._request_matches_task>]>
```
Showing that the first `_make_matches_task` was scheduled.
