### ISSUE TITLE
Notify participants of followups.

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#300]
[Nicole wrote Scott this fantastic Follow-up and I'm not sure he ever knew about it!](https://www.pennyuniversity.org/chats/29) and he was never aware of it. This has happened since then as well.

# TODO
- [x] Run a daily script to notify people of followups that occurred the day before. Any participant of any chat with followups will be notified in slack. Eventually this would be great for emails as well.
  - [x] Create query. 
    * Make sure that we exclude updates that are from the user. Current one doesn't do this. ~ Done one client side
    * [Prototype here](https://github.com/penny-university/penny_university/compare/JnBrymn/2020.08.02/300/NotifyOfFollowups?expand=1)
  - [x] Figure out how to schedule it for only once daily. (piggy back on current 10 minute `background_tasks` or create new thing?) ~ I'll run this every day over the updates from the day before. I'll do this by adding a job on our Heroku Scheduler https://dashboard.heroku.com/apps/penny-university/scheduler?job=new
  - [x] Figure out Blocks ~ just do something simple like `slack.chat_postMessage(channel='#general',text='Your <!date^1392734382^{date_short}|TODO! add date string> Penny Chat "Lightning Talks" has <http://example.com|new follow-ups from Frank and Jimmy>') `
  - [x] Assemble ~ starting in users/management/commands/follow_up_notification.py
  - [x] Send to #penny-labs?
  - [x] Test and Cleanup
  - [x] Document - the belongs in our product catalog
  - [x] Ship
  - [x] Setup and run in Heroku Scheduler
  - [x] Send full history to everyone as a one-time-only run
- [x] Consider also notifying any channels that were invited to the chat. This would engage people that weren't in the original chat and provide a little FOMO. ~ Decided not to do
- [x] Runs special 1-time-only script over the past month

**Comment by JnBrymn** [comment]
I fixed the above issues. And all the boxes are checked. Closing.
