### ISSUE TITLE
Privacy Functionality 

### ISSUE THREAD

**Issue by deadbender** [penny-university/penny_university#321]
## Description

**Private Chat**
- visible on participant's profile, if the participant is the logged in user
- not visible on /chats to any users 
- if user accesses chat URL they do not have access to, send to 403

**Public Chat**
- visible to all signed in and not signed in users on profiles or /chats

**Etc**
- users should be able to click a checkbox in the `/penny chat` form to set private or public status
  - should eventually be editable from web app as well

## TODO
- [x] ~~Add `visibility` field to `PennyChat` in pennychat/models.py~~
  ~~* type `IntegerField`~~
  ~~* `choices` should be `PRIVATE = 10` and `PUBLIC = 20` (maybe there will be other types of visibility later)~~
  ~~* Update the db with `./manage.py makemigrations` then `./manage.py migrate`~~
- [x] ~~Add `public_or_participated` method to `PennyChat` in pennychat/models.py~~
  ~~* It will have an argument for `user`~~
  ~~* It will return a queryset of all Penny Chats that are `visibility = PUBLIC` or something attended by the `user`. This query will be a pain in the butt to write.~~
- [x] ~~In `PennyChatViewSet` in pennychat/views.py figure out how to use that filter to narrow down the list of penny chats~~
~~- [x] Within `bot.processors.pennychat.PennyChatBotModule.create_penny_chat` add a Private checkbox.~~
- [ ] Private Checkbox Styling
- [x] ~~Within `bot.processors.pennychat.PennyChatBotModule.submit_details_and_share` save the Private checkbox to the  `visibility` field of the PennyChatInvitation.~~

## TESTS

- [ ] Fix original tests with issues 

- [ ] Test to make sure `visibility` exists in `PennyChat` model
- [ ] Test to make sure private chats aren't visible to non participating users
- [ ] Test to make sure that participated chats are visible to participated users, even when private
