### ISSUE TITLE
Move to Heroku

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#36]
Would automatically take care of lots of issues:
- #14 
- #28 
- #30 

# TODO 
- [x] Set up codebase so that you can successfully 
  - [x] deploy to heroku ~ https://penny-university.herokuapp.com
  - [x] run app and tests locally
  - [x] test in our github actions
- [x] make sure bot logs are visible ~ you can do `heroku run tail -f messages.log`
- [x] make slack hook API connect (have to verify response) ~ [did it](https://github.com/penny-university/penny_university/issues/36#issuecomment-532930998), since revised to www.pennyuniversity.org. Also changed the interactive hook.
- [x] repoint DNS to heroku ~ [some trouble](https://github.com/penny-university/penny_university/issues/36#issuecomment-533148679) but [finally figured it out]()
- [x] Get persistent heroku dynos ~ [done](https://github.com/penny-university/penny_university/issues/36#issuecomment-532938909_
- [x] Document:
  - account login
  - where configs are hiding
- [x] Transfer User table to new server ~ [proof](https://github.com/penny-university/penny_university/issues/36#issuecomment-533387400)
- [x] Turn off other server ~ [proof](https://github.com/penny-university/penny_university/issues/36#issuecomment-533388247)

**Comment by JnBrymn** [comment]
![image](https://user-images.githubusercontent.com/566533/65206948-d6a93700-da55-11e9-9036-b5f183463c56.png)

**Comment by JnBrymn** [comment]
![image](https://user-images.githubusercontent.com/566533/65208760-9f3d8900-da5b-11e9-89ad-b148f262c6fa.png)

**Comment by JnBrymn** [comment]
Some trouble in repointing the domain.
![image](https://user-images.githubusercontent.com/566533/65251569-2a02a000-dabd-11e9-8261-a88b6f47f550.png)
This appears to work correctly because www.pennyuniversity.org loads.

![image](https://user-images.githubusercontent.com/566533/65251640-46064180-dabd-11e9-814e-22688a5f1abc.png)

This one ^ doesn't work though b/c pennyuniversity.org doesn't redirect to www.pennyuniversity.org

**Comment by JnBrymn** [comment]
DNS done. 

Proof: ssh into digital ocean server, double check that the app is NOT running. I can then
* go to www.pennyuniversity.com and see the website page load
* go to pennyuniversity.com and see it redirect to www.
* I can click a "What would you like to learn?" and get a response from the server. I can also save it and then click the button again and see it again.

**Comment by JnBrymn** [comment]
Users transferred 
```
select user_name from "user";
   user_name    
----------------
 jb
 nick.chouard
 kazshak
 adamtaylor0795
```

**Comment by JnBrymn** [comment]
Destroyed Digital Ocean server
![image](https://user-images.githubusercontent.com/566533/65296864-869ca400-db2b-11e9-8875-08679a6e3902.png)

**Comment by JnBrymn** [comment]
all tasks completed, closing
