### ISSUE TITLE
Upgrade bot base code

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#52]
# TODO
- [ ] Upgrade bot base to pattern below
- [ ] Set it up to modify the message rather than just filter based on message. Rather than `if filter_func(message=message) ...` do `message = filter_func(message=message)` and `if message`
- [ ] Change names: 
  - call `processor_filter` as `processor_decorator` (because it can do more than just filter - it can modify)
  - call `filter_func` something better. `preprocessor` ?
- [ ] Add `@functools.wraps` to fix wrapped function naming, etc.
- [ ] Consider also modifying `BotModule` to have ordered functions and the ability to stop execution if a processor has handled work. (I don't know how to do this. It probably belongs in a different ticket.)

# Details
I just discovered this 

```python
def processor_filter(filter_func):
    def decorator(*dec_args, **dec_kwargs):
        if dec_args and callable(dec_args[0]):
            processor = dec_args[0]
            def wrapped_processor(*args):
                if isinstance(args[0], Message):
                    message = args[0]
                else:
                    message = args[1]
                if filter_func(message=message):
                    return processor(*args)
        else:
            new_filter_func = partial(filter_func, *dec_args, **dec_kwargs)
            return processor_filter(new_filter_func)

        return wrapped_processor
    return decorator    
```

This combines and simplifies the functionality of `event_filter_factory` and `event_filter`. With this you can do 

```python
@processor_filter
def from_user(user, message):
    return message.user == user

@processor_filter
def contains_kittens(message):
    return 'kittens' in message.text
```

Which provides these decorators

```python
@from_user('will')  # decorator that takes parameters
def processor(message):
    will_only_stuff()

@contains_kittens # decorator that takes no parameters
def processor(message):
    kitten_only_stuff()
```

Amazingly you can also use decorators to create other derived decorators:
```python
from_will = from_user('will')

@from_will
def processor(message):
    will_only_stuff()
```

Easier to read, easier to write, more flexible, less to remember.

**Comment by nchouard** [comment]
@JnBrymn merge with #54?
