### ISSUE TITLE
Upgrade bot decorator code

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#54]
# TODO
- [x] Add `event_process_decorator` to `bot/processors/base.py` and add tests
- [x] Convert other code to use `event_process_decorator`
- [x] Remove dead code
  - [x] `class Event`
  - [x] `process_all_events`
  - [x] `event_filter`
  - [x] `event_filter_factory`
