### ISSUE TITLE
MVP (epic)

### ISSUE THREAD

**Issue by nchouard** [penny-university/penny_university#55]
# Description
We intend to replace the google forum. This involves creating the following chunks. Goal - turn these boxes into tickets (and feel free to rearrange anything below so that it makes sense).

[Refer to our PennyHack conversation](https://docs.google.com/document/d/1eYrsqk87FhxZGjKz1l3ynCEwkDxUA_QK_f3Ts94ThqA/edit#heading=h.mfu0i4gz0ivq)

## MVP
- [x] Penny Chat List
  - [x] Infinite scroll #150 
  - [x] Detail overview
- [x] Penny Chat Detail
  - [x] Name, date, description
  - [x] Follow Up List on Penny Chats
    - [x] Create and edit follow ups
- [x] User Profile
  - [x] REST endpoint #188 
  - [x] List of penny chat participations #187 
  - [x] Profile Page edit personal information # 187
- [x] User Registration/Log In #183 
- [x] Create Reminder to do Penny Chat Followup #191
- [x] User email verification 
  - [x] Backend #214 
  - [x] Frontend #151 
- [x] UserProfile refactor #213 

## Roll Out
- [x] Deploy React App ~ 2020.05.30 successfully loaded https://www.pennyuniversity.org/chats/8
- [x] Make sure email flow works ~ https://github.com/penny-university/penny_university/issues/224 partially fulfills this
- [x] Load Data and Make forum read-only
- [x] ~Write web page / FAQ / intro in prep for new people coming to the webside~ ~ decided to do it soon but not gate MVP on this
- [x] Let people know 🎉 https://github.com/penny-university/penny_university/issues/73

Decided that this doesn't gate MVP:
```
## MVP Bonus
- [ ] Organizer can update Penny Chat details
- [ ] Like Penny Chats/Follow Ups #185
- [ ] Share Link #186
- [ ] Details of interests #232
- [ ] User Follow Ups list (Chat List UI improvements) #231

## Future Steps
- [ ] Search
- [ ] Calendar
- [ ] Notifications/Reminders
```

**Comment by CoreyAR** [comment]
Based on the comments on ticket #186 I think it should be moved out of the MVP.
We could start with a stripped down version of the feature which supports copying to a clipboard but the value is limited since we'd be copying the url available from the browser

**Comment by JnBrymn** [comment]
All boxes checked - closing.
