### ISSUE TITLE
Penny Chat Command (epic)

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#63]
## Soon
  - [x] ~Fix calendar invite (probably make event on Penny U calendar)~ ~ https://github.com/penny-university/penny_university/issues/81
  - [x] Fix bug where chat is shared with one room multiple times (STR - share to more than 1 channel) ~ Fixed in https://github.com/penny-university/penny_university/pull/67
  - [x] Require a chat to be shared with SOMEONE ~ https://github.com/penny-university/penny_university/issues/68
  - [x] Add timezone knowledge to penny chat flow (and let users know in text) ~ [already done](https://github.com/penny-university/penny_university/commit/2062266098e27ef4c7967f5516cd4f88f0feeb91)  
- [x] When a user finished with the chat creation modal improve the next step so that the users understand they are reviewing details

## Next
- [ ] When inviting people to participate in a chat, make them click an accept button to RSVP (yes, maybe, no). https://github.com/penny-university/penny_university/issues/117 Why:
  - When an entire channel is invited, you don't know who will actually be attending.
  - When a meeting date is changed only the attendees will be notified.
- [ ] Notify organizer as people RSVP https://github.com/penny-university/penny_university/issues/117
- [ ] Make it possible to edit chat details and update attendees (especially date/time) ~ https://github.com/penny-university/penny_university/issues/128
- [ ] Remind attendees of details just before the chat ~ https://github.com/penny-university/penny_university/issues/132
- [ ] Remind attendees after the chat to do their review
- [ ] Create Penny Chat Follow-up flow (draws them into the web app)
- [ ] Extract the "Invite users" and "Invite channels" our of the Penny Chat form and instead do them in Slack AND allow people to type email addresses when the users aren't in our slack.

## Other ideas to consider:
- [ ] Add google hangout
- [ ] Add google doc
- [ ] When people accept a chat (or when inviting them to participate), bring them all into one room so they have social pressure.
- [ ] Figure out how to connect to google cal in a way that doesn't leak email addresses.

**Comment by nchouard** [comment]
@JnBrymn What should we do with this ticket? Is it still useful?

**Comment by JnBrymn** [comment]
closing it
