### ISSUE TITLE
Welcome Back Event

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#73]
# TODO
- [x] Email/slack all members that have been active in the past (below) a link to their "my chats" page.
  - [x] Write text for email. ~ https://github.com/penny-university/penny_university/blob/1d848192086c34dfbfd4f1ee3ef3b0da933d0838/users/templates/users/welcome_back_email.txt
  - [x] Create HTML template. (Probably using https://beefree.io/bee-pro/)
  - [x] Create manage command to gather all web app Users as well as a list of emails for the forum users and send an email. ~ just have to add templating to the HTML version
  - [x] Get reviewed, and then send to slack and forum users.
- [x] Help Nick update FAQ
- [x] Post fanfare in Slack.
- [x] Set up a few different large-group penny chats to let people know what's happening. ~ https://github.com/penny-university/penny_university/issues/73#issuecomment-654574757
- [x] Video walkthrough of features for the FAQ and drop that into slack with a TL;DR "use `/penny chat`" ~ https://penny-university.slack.com/archives/C41G02RK4/p1596637191220200

**Comment by JnBrymn** [comment]
Outline for Penny Chat classes.
* Intro: 15 minutes to talk about what's new at Penny U followed by 15 minutes of questions and brainstorming.
* Context:
  * Penny U is _your_ social learning community and we've been looking for ways to build a platform to help bolster the good culture that we've seen emerge in the community.
  * The behavior that we've seen has been 
    * Organizing in Penny Chats - scheduling, inviting, and meeting.
    * Writing Penny Chat followups
  * Historically the "platform" has been Slack, Zoom, and the Google Forum.
  * But these tools have lead to difficulties:
    * Coordinating people with tons of messages is inconvenient.
    * Writing a follow-up the the Google forum is awkward.
* So we're building software to resolve these problems.
  * `/penny chat` to create a chat and invite channels or individuals (make sure to include video meeting link)
  * Get notified as people accept or decline invitations.
  * Everyone that RSVPed gets a slack reminder just an hour before the notification.
  * At the end of the meeting there is a slack reminder to write a followup. (Tell "how Penny U says thanks" story.)
  * And then /profile/X becomes a trophy room of all the interesting conversations you've had, things you've learned, and people you've spoken with.
  * Finally /chats/ is a good place to see all the interesting things that have happened in the past and upcoming events.
* In the future: 
  * scheduling
  * engagement (find an upcoming chat for you)
  * search
  * calendar?
* Q&A
* Anyone want to help?

**Comment by JnBrymn** [comment]
# Proof of Correctness
Three variants:
1) Only email known
![image](https://user-images.githubusercontent.com/566533/87230974-e002e780-c378-11ea-9b65-95237ab5a7fb.png)
Links are correct. The greeting appropriately doesn't include name. "your own profile page" appropriately does not have link.

2) User name is known, but they aren't active enough to have own profile
![image](https://user-images.githubusercontent.com/566533/87231040-71725980-c379-11ea-9900-7cfd3b5988b6.png)
Includes user's name. The have correct profile link. They appropriately don't have a paragraph about their historic activity.

3) User name is known and they have been active.
![image](https://user-images.githubusercontent.com/566533/87231096-dc239500-c379-11ea-990f-d19e6375895a.png)
Includes user's name. Includes paragraph about historic activity. 2 profile links are correct.

**Comment by JnBrymn** [comment]
all boxes checked!
