### ISSUE TITLE
React App (epic)

### ISSUE THREAD

**Issue by nchouard** [penny-university/penny_university#76]
Make our forum a React/Redux application

- [x] Create React only application (dummy data, no redux) #77 
- [x] Connect to API (encompassed in #97)
- [x] Add Redux to manage state #97 
- [x] User Auth #183
- [x] Testing #116 
- [x] Deploy with django app
- [ ] Move homepage to be part of React App
- [ ] Server side rendering for SEO

**Comment by JnBrymn** [comment]
Done enough.

**Comment by JnBrymn** [comment]
🥳
