### ISSUE TITLE
Get `/penny chat` calendar events working.

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#81]
# Goal
The current penny chat calendar invite invites people to their own calendar event but you don't know who else is coming. Instead we want to make an invite for an event on the Penny U calendar for everyone.

# TODO
- [x] Is the experience ok if you get invited to a GCal event but don't have a google email? ~ not bad, you get to RSVP and you have the option to sign up for an account - I wish there was a way to get a calendar URL to stick onto your own calendar if you're not a GCal person
- [x] If I create a public Penny U calendar event and invite people, does that make their emails public? ~ ***OOPS!***
  * If the event is public, then everyone will be able to see their email addresses
  * If the event is private, then:
    * People that are invited will be able to see everyone's email addresses
    * People that aren't invited will not be able to see the title or description of the event
- [ ] Eventually we'll want private events that aren't on any public calendar. Can we do that when using the GCal events?
- [ ] If we make the calendar event programmatically, how can the organizer edit the contents?
- [ ] Read the API https://developers.google.com/calendar/overview
- [ ] Be able to make an event on the Penny U calendar. 
- [ ] Be able to invite people
- [ ] Create behavior in bot to create and invite people.
- [ ] Add google doc and google hangout to event.

**Comment by JnBrymn** [comment]
blocked b/c other stuff is more important

**Comment by JnBrymn** [comment]
Because many people don't use Google cal and it's too easy to share email addresses, I don't think I want to invest the time needed to get this right.
