### ISSUE TITLE
Remove PennyChat user and add M2M between PennyChat and User

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#87]
# TODO
- [x] remove user field from PennyChat - this used to indicate the creator of the Chat but in the forum data dump we don't truly have this data anyway
- [x] create a M2M between PennyChat and User indicating that they were participants. Participation should have a `type` field with values `{ organizer, invitee, attendee (trumps invitee)}`
- [x] ~fix  `./manage.py import_users_from_slack`~ ~ nothing to change
- [x] fix `./manage.py import_google_forum`
- [x] ~remove all uses of user_tz from pennychat~ decided not to because it was so tangled up with pennychat invitation creation - maybe later
- [ ] manually test things and add unit tests for anything lacking
- [x] change `__repr__` for objects to something that just dumps out `json.dumps(object.__dict__)` so that we don't get errors when we print out objects after changing fields
