### ISSUE TITLE
Clarify /penny chat share step

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#93]
# Description
The `/penny chat` share step would make more sense to users if they see the exact message that the users that they share to will see. This will also DRY the processor code because we can reuse one message template within another.

We will also adjust the flow so that upon the first pennychat form submission

# TODO
- [x] ~Consider removing the `user` and `user_tz` field from the PennyChat model if we don't need it any more.~ ~ considered - decided not to because it turns into too much refactoring
- [x] Validate that user fields are set correctly (either slack_id or (email AND slack_team_id) or both)
- [x] When user submits form, show them what the share message will look like and who they will share it to.
- [x] Make sure the actual share template is used inside the save template so that we DRY the code a bit
- [x] Add participants as Invitees and Organizer
- [x] Try color quotes to draw attention to the invite. ~ Only way I found to use color was with attachments [which are semi-deprecated](https://api.slack.com/messaging/composing/layouts#attachments)
- [x] Move `user.utils` under `user.models`
- [x] Test
  * `get_or_create_by_slack_ids`
  * That participants and users are correctly added during pennychat create flow.
- [ ] Ship

**Comment by JnBrymn** [comment]
# Evidence of correctness
This is the share preview
![image](https://user-images.githubusercontent.com/566533/72128868-e8cb2000-3339-11ea-87db-8d28a7df2179.png)

Once shared you get
![image](https://user-images.githubusercontent.com/566533/72128936-157f3780-333a-11ea-9c9d-b64aa67315bf.png)

Also the users and organizers associated with this chat have been created and the Participant connection between the users and penny chat are created correctly. This also is supported by unit tests.
