### ISSUE TITLE
Add something like "user" back to PennyChat serialization for API

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#95]
# Todo
- [x] ~Create SimpleUser serializer~ ~ decided to reused existing UserProfile serializer
- [x] Create Participant serializer that embeds 1 SimpleUser
- [x] Create a list of Participants for a penny chat.
- [x] Add chat list for users
- [x] Make the "role" for participants and userchats pretty print.
- [x] Add tests (see Followup tests).

# Docs
* [PennyU API design doc](https://github.com/penny-university/penny_university/blob/master/docs/achitecture_and_design/api_design.md)
* [Django REST docs on relation serializers](https://www.django-rest-framework.org/api-guide/relations/#slugrelatedfield)

# Description
Since we're getting rid of the notion of a PennyChat user and moving to participants with roles. I chose to remove user from the serializer. https://github.com/penny-university/penny_university/pull/94

BUT, we do need something to replace it in the serialization. Maybe "organizer"? This would make use of the value in the Participants table.

**Comment by JnBrymn** [comment]
@nchouard I think I'll take this so that I can try my hand at rest_framework and so that we can have participants listed in the penny_chats. Does the "participants" sections in the API design doc still seem sensible? https://github.com/penny-university/penny_university/blob/master/docs/achitecture_and_design/api_design.md

**Comment by JnBrymn** [comment]
I have taken control of John.

**Comment by JnBrymn** [comment]
Nick has the best ideas... Maybe I should pass this issue along to him?
